# generated by datamodel-codegen:
#   filename:  api-docs.json
#   timestamp: 2026-03-02T15:59:16+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Contact(BaseModel):
    fax: str | None = None
    mail: str | None = None
    telephone: str | None = None
    website: str | None = None


class GemeindeDTO(BaseModel):
    b: float | None = None
    l: float | None = None
    n: str | None = None
    p: str | None = None


class Location(BaseModel):
    address: str | None = None
    city: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    postalCode: str | None = None


class OfferInformation(BaseModel):
    selfService: bool | None = None
    service: bool | None = None
    unattended: bool | None = None


class Day(Enum):
    MO = "MO"
    DI = "DI"
    MI = "MI"
    DO = "DO"
    FR = "FR"
    SA = "SA"
    SO = "SO"
    FE = "FE"


class OpeningHour(BaseModel):
    day: Day
    from_: str | None = Field(None, alias="from")
    to: str | None = None


class PaymentArrangements(BaseModel):
    accessMod: str | None = None
    clubCard: bool | None = None
    clubCardText: str | None = None
    cooperative: bool | None = None


class PaymentMethods(BaseModel):
    cash: bool | None = None
    creditCard: bool | None = None
    debitCard: bool | None = None
    others: str | None = None


class Price(BaseModel):
    amount: float | None = None
    fuelType: str
    label: str | None = None


class Type(Enum):
    PB = "PB"
    BL = "BL"


class Region(BaseModel):
    cities: list[str] | None = None
    code: int | None = None
    name: str | None = None
    postalCodes: list[str] | None = None
    subRegions: list[Region] | None = None
    type: Type | None = None


class BezirkDTO(BaseModel):
    c: int | None = None
    g: list[GemeindeDTO] | None = None
    n: str | None = None


class BundeslandDTO(BaseModel):
    b: list[BezirkDTO] | None = None
    c: int | None = None
    n: str | None = None


class GasStationPublic(BaseModel):
    contact: Contact | None = None
    distance: float | None = None
    id: int | None = None
    location: Location | None = None
    name: str
    offerInformation: OfferInformation | None = None
    open: bool | None = None
    openingHours: list[OpeningHour] | None = None
    otherServiceOffers: str | None = None
    paymentArrangements: PaymentArrangements | None = None
    paymentMethods: PaymentMethods | None = None
    position: int | None = None
    prices: list[Price] | None = None
